AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB tables
Parameters:
  TableName:
    Type: String
    Description: Name of the table
  ReadUnits:
    Type: Number
    Description: The number of Read Units
  WriteUnits:
    Type: Number
    Description: The number of Write Units

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "ckid"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "ckid"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadUnits
        WriteCapacityUnits: !Ref WriteUnits
      TableName: !Ref TableName

Outputs:
  TableName:
    Description: Name of the DynamoDB Table
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub "${AWS::StackName}-TableName"
  TableArn:
    Description: Arn of the DynamoDB Table
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub "${AWS::StackName}-TableArn"