AWSTemplateFormatVersion: 2010-09-09
Description: ECR Repositories
Resources:
  Repos:
    Type: IgnoreMe::ECR::Repository
    Properties:
      Repositories:
        - dummy-passthrough-api
        - feed-api
        - list-api
        - order-api
        - register-api
        - validate-api
        - public-site
        - happiness-api

Transform:
  - ECRExpander