AWSTemplateFormatVersion: 2010-09-09
Description: The ECS Service
Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  TaskDefinitionStack:
    Type: String
    Description: The stack of the task definition
  Cluster:
    Type: String
    Description: The name of the ECS Cluster
  SubnetIDs:
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>
    Description: The Parameter store value containing the Subnet IDs to deploy in
  SecurityGroups:
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::SecurityGroup::Id>>
    Description: The Security Groups to be used
  RegistryStack:
    Type: String
    Description: The ARN of the service discovery registry
  DesiredCount:
    Type: Number
    Description: The number of instances we want to run

Resources:
  ServiceRegistry:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      Description: !Sub "${ServiceName} discovery"
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 60
        RoutingPolicy: WEIGHTED
      Name: !Ref ServiceName
      NamespaceId:
        Fn::ImportValue: !Sub "${RegistryStack}-InternalNamespace-ID"

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: !Ref DesiredCount
      # HealthCheckGracePeriodSeconds: 10
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: !Ref SecurityGroups
          Subnets: !Ref SubnetIDs

      PlatformVersion: LATEST
      PropagateTags: SERVICE
      # Role: String
      ServiceName: !Ref ServiceName
      ServiceRegistries:
        - ContainerName: !Ref ServiceName
          RegistryArn: !GetAtt ServiceRegistry.Arn
      TaskDefinition:
        Fn::ImportValue: !Sub "${TaskDefinitionStack}-Arn"

# Outputs: